#!/usr/bin/env bash

# standard invocation of sitegen.py

# while getopts "t:r:p" OPT
# do
#     case "$OPT" in
#       r)
#         VERSION="$OPTARG"
#         ;;
#       t)
#         ISABELLE_TOOL="$OPTARG"
#         ;;
#       p)
#         USE_PYTHON_3=true
#         ;;
#     esac
# done
# shift $((OPTIND-1))

# set_isabelle_tool

# echo "Checking presence of Hugo ..."

# case "$(uname -s)" in
#   Darwin)
#     echo "Running on macOS, using system python"
#     PYTHON="/usr/bin/python"
#     ;;
#   *)
#     if [ "$USE_PYTHON_3" = false ]; then
#       echo "Running on Linux, trying to find Python 2.x"
#       PYTHON="$(which python2 2> /dev/null)"
#       if [ -z "$PYTHON" ]; then
#         PYTHON="$(which python 2> /dev/null)"
#       fi
#     else
#       echo "Running on Linux, trying to find Python 3.x"
#       PYTHON="$(which python3 2> /dev/null)"
#     fi
#     ;;
# esac

# if [ ! -f "$PYTHON" ]; then
#   fail "No suitable Python found"
# else
#   echo "Found Python at '$PYTHON'"
# fi


echo "Running sitegen ..."
cd admin/hugo && hugo

cp -r public/* ../../web/
