#!/usr/bin/env bash

# For verbose output, pass -v

_V=0

while getopts "v" OPTION
do
  case $OPTION in
    v) _V=1
       ;;
    *) 
       ;;
  esac
done

function log () {
    if [[ $_V -eq 1 ]]; then
        echo "$@"
    fi
}

start=$(date +%s)

log "Checking presence of Python ..."
PYTHON="$(command -v python3 2> /dev/null)"

if [ ! -f "$PYTHON" ]; then
  echo "No suitable Python found"
  exit 1
else
  log "Found Python at '$PYTHON'"
fi

log "Checking presence of Pip ..."

if $PYTHON -m pip --version |& grep -q 'No module named pip'; then
  echo "Error: PIP not installed. See https://pip.pypa.io/en/stable/installing/"
  exit 1
else
  log "Found Pip"
fi

log "Installing dependancies ..."
$PYTHON -m pip install -r admin/requirements.txt -q

log "Checking presence of Hugo ..."
HUGO="$(command -v hugo 2> /dev/null)"

if [ ! -f "$HUGO" ]; then
  echo "Error: Hugo not installed. See https://gohugo.io/getting-started/installing/"
  exit 1
else
  log "Found Hugo at '$HUGO'"
fi

log "Export metadata ..."
$PYTHON admin/exportMetadata.py

cd admin/hugo && $HUGO

end=$(date +%s)
runtime=$((end-start))
echo "Total time: $runtime seconds" 